USE handy_tutor;
DROP TABLE SUBTITLE;

CREATE TABLE SUBTITLE (
        VIDEO_KEY VARCHAR(20) NOT NULL,
        KOREAN VARCHAR(255) NOT NULL,
        ENGLISH VARCHAR(255) NOT NULL,
        ROLE INT NOT NULL,
        TIME INT NOT NULL,
        FOREIGN KEY(VIDEO_KEY) REFERENCES VIDEO (VIDEO_KEY) ON DELETE CASCADE
);
LOAD DATA LOCAL INFILE 'friends_subtitle.csv' INTO TABLE SUBTITLE FIELDS TERMINATED BY ',';
