CREATE TABLE VIDEO (
	VIDEO_KEY VARCHAR(20) NOT NULL,
	VIDEO_TITLE VARCHAR(255) NOT NULL,
	PRIMARY KEY(VIDEO_KEY)	
);

CREATE TABLE SUBTITLE (
	VIDEO_KEY VARCHAR(20) NOT NULL,
	KOREAN VARCHAR(255) NOT NULL,
	ENGLISH VARCHAR(255) NOT NULL,
	ROLE INT NOT NULL,
	TIME INT NOT NULL,
	FOREIGN KEY(VIDEO_KEY) REFERENCES VIDEO (VIDEO_KEY) ON DELETE CASCADE
);
